version: "3"
services: 
  api:
    build: .
    depends_on:
      - postgres
    ports: 
      - 6996:8000
    volumes:
      - ./:/usr/src/app
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    # env_file:
    #   - ./.env
    environment:
      - DATABASE_HOSTNAME=postgres
      - DATABASE_PORT=5432
      - DATABASE_PASSWORD=12345
      - DATABASE_NAME=fastapi
      - DATABASE_USERNAME=postgres
      - SECRET_KEY="abc"
      - ALGORITHM="HS256"
      - ACCESS_TOKEN_EXPIRE_MINUTES=30

  postgres:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=12345
      - POSTGRES_DB=fastapi
    volumes:
      - postgres_db:/var/lib/postgresql

volumes:
  postgres_db: